### ISSUE TITLE
no chinese language file generated

### ISSUE THREAD

**Issue by WitheredWinter** [nulli0n/MoneyHunters-spigot#10]
in the spigot page,you said that the chinese language is available,but when i load this plugin,no relevant files generated.
where can i download the chinese version?

**Comment by WitheredWinter** [comment]
![uTools_1675519619523](https://user-images.githubusercontent.com/123742753/216772175-14304eaa-ccbf-4a71-8c4c-555712f37753.png)

no chinese:
![image](https://user-images.githubusercontent.com/123742753/216772194-bb87bcd5-c179-4fe3-bbd7-5a22b30a0374.png)

**Comment by RAURORA2** [comment]
ME TOO

**Comment by nulli0n** [comment]
Seems it was there sometime ago and was removed due to being heavy outdated. Language information corrected. Chinese translation is not available at this time.
