### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by masmc05** [nulli0n/MoneyHunters-spigot#8]
a looot of 
  [Sun 14:03:08 INFO  MoneyHunters] harvest
  [Sun 14:03:08 INFO  MoneyHunters] harvest
  [Sun 14:03:08 INFO  MoneyHunters] harvest
  spam
please remove 
https://github.com/nulli0n/MoneyHunters-spigot/blob/252c23a0eb35569e775836466a98d78ae2d13395/Pro/src/main/java/su/nightexpress/moneyhunters/pro/manager/job/listener/JobListenerGeneric.java#L81
and 
https://github.com/nulli0n/MoneyHunters-spigot/blob/252c23a0eb35569e775836466a98d78ae2d13395/Pro/src/main/java/su/nightexpress/moneyhunters/pro/manager/job/listener/JobListenerGeneric.java#L79

**Comment by nulli0n** [comment]
Fixed.
